export const spriteData = [
  {
    id: "normal_stand",
    name: "Normal: Stand",
    filename: "normal_stand.png",
    category: "Base Clone",
    subjectId: "SUB-01",
    pose: "Standing neutral with arms straight down and a small, open triangular mouth.",
    clothing: "Base Outfit: A yellow short-sleeved shirt, straight-leg blue pants, and dark shoes.",
    reference: "Original character - Default default look, does not reference an outside character.",
    stability: "100.0%",
    hazardLevel: "Safe",
    powerLevel: "120",
    dnaSequence: "ATG-GCT-AAC-TGA-GCT-99"
  },
  {
    id: "normal_questioning",
    name: "Normal: Questioning",
    filename: "normal_questioning.png",
    category: "Base Clone",
    subjectId: "SUB-02",
    pose: "Right hand on chin, furrowed eyebrow, looking perplexed as if analyzing a formula.",
    clothing: "Base Outfit: A yellow short-sleeved shirt, straight-leg blue pants, and dark shoes.",
    reference: "Original character - Default default look, does not reference an outside character.",
    stability: "98.5%",
    hazardLevel: "Safe",
    powerLevel: "150",
    dnaSequence: "ATG-GCT-AAC-TGA-TGG-88"
  },
  {
    id: "normal_one",
    name: "Normal: One Point",
    filename: "normal_one.png",
    category: "Base Clone",
    subjectId: "SUB-03",
    pose: "Smiling with the right index finger pointing up to make a brilliant point or observation.",
    clothing: "Base Outfit: A yellow short-sleeved shirt, straight-leg blue pants, and dark shoes.",
    reference: "Original character - Default default look, does not reference an outside character.",
    stability: "99.2%",
    hazardLevel: "Safe",
    powerLevel: "220",
    dnaSequence: "ATG-GCT-AAC-TGA-CGT-77"
  },
  {
    id: "normal_angy",
    name: "Normal: Angy",
    filename: "normal_angy.png",
    category: "Base Clone",
    subjectId: "SUB-04",
    pose: "Frowning with a red, pulsing anime-style anger vein glowing on the forehead.",
    clothing: "Base Outfit: A yellow short-sleeved shirt, straight-leg blue pants, and dark shoes.",
    reference: "Original character - Default default look, does not reference an outside character.",
    stability: "85.0%",
    hazardLevel: "Unstable (Mild)",
    powerLevel: "480",
    dnaSequence: "ATG-GCT-AAC-TGA-CCC-FE"
  },
  {
    id: "normal_uhm",
    name: "Normal: Uhm Actually...",
    filename: "normal_uhm.png",
    category: "Base Clone",
    subjectId: "SUB-05",
    pose: "Right index finger raised with an open mouth showing buck teeth (the classic 'Uhm, actually...' nerd posture).",
    clothing: "Base Outfit: A yellow short-sleeved shirt, straight-leg blue pants, and dark shoes.",
    reference: "Original character - Default default look, does not reference an outside character.",
    stability: "95.1%",
    hazardLevel: "Annoying but Safe",
    powerLevel: "180",
    dnaSequence: "ATG-GCT-AAC-TGA-ATT-23"
  },
  {
    id: "normal_nudge_glasses",
    name: "Normal: Smart Glasses",
    filename: "normal_nudge_glasses.png",
    category: "Base Clone",
    subjectId: "SUB-06",
    pose: "Pushing up the bridge of the glasses with the right index finger, accompanied by a bright, white star lens flare.",
    clothing: "Base Outfit: A yellow short-sleeved shirt, straight-leg blue pants, and dark shoes.",
    reference: "Original character - Default default look, does not reference an outside character.",
    stability: "99.9%",
    hazardLevel: "Safe (Highly Calculative)",
    powerLevel: "600",
    dnaSequence: "ATG-GCT-AAC-TGA-GGG-AA"
  },
  {
    id: "american_boy",
    name: "American Boy",
    filename: "american_boy.png",
    category: "Pop Culture Variant",
    subjectId: "SUB-07",
    pose: "Smiling broadly and proudly holding up a heavy white '#1 DAD' coffee mug.",
    clothing: "A blue business suit, white collared shirt, black tie, and a tiny detailed Thai flag lapel pin.",
    reference: "Stan Smith from American Dad!. Representing patriotic fatherly energy.",
    stability: "90.4%",
    hazardLevel: "Moderate (Patriotic Outbursts)",
    powerLevel: "750",
    dnaSequence: "USA-GCT-AAC-TGA-DAD-01"
  },
  {
    id: "sciene_guy",
    name: "Science Guy",
    filename: "sciene_guy.png",
    category: "Pop Culture Variant",
    subjectId: "SUB-08",
    pose: "Smiling with glowing green radioactive drool on the chin, holding a green chemical glass flask/bottle in the left hand.",
    clothing: "A classic white lab coat worn over a light blue t-shirt, brown pants, and a black belt with a gold buckle.",
    reference: "Rick Sanchez from Rick and Morty. Represents infinite intelligence and chronic cynicism.",
    stability: "61.3%",
    hazardLevel: "High Risk (Highly Radioactive)",
    powerLevel: "9999",
    dnaSequence: "RCK-MCT-A12-TGA-WUB-BA"
  },
  {
    id: "science_guy_flip",
    name: "Science Guy: Volatile",
    filename: "science_guy_flip.png",
    category: "Pop Culture Variant",
    subjectId: "SUB-09",
    pose: "Flipping the middle finger with the right hand to express existential defiance, while holding the green bottle in the left.",
    clothing: "A classic white lab coat worn over a light blue t-shirt, brown pants, and a black belt with a gold buckle.",
    reference: "Rick Sanchez from Rick and Morty. The ultimate multi-dimensional rebellious state.",
    stability: "34.8%",
    hazardLevel: "Extremely Volatile (Bio-Hazard)",
    powerLevel: "99999",
    dnaSequence: "RCK-MCT-A12-TGA-FLIP-FU"
  },
  {
    id: "family_man",
    name: "Family Man",
    filename: "family_man.png",
    category: "Pop Culture Variant",
    subjectId: "SUB-10",
    pose: "Standing confidently and cheerfully with hands resting firmly on the hips.",
    clothing: "A white short-sleeved button-up shirt, bright green pants, brown shoes, and a black belt with a gold buckle.",
    reference: "Peter Griffin from Family Guy. Exudes absolute confidence and comical simplicity.",
    stability: "87.0%",
    hazardLevel: "Low Risk (Chaos Magnet)",
    powerLevel: "320",
    dnaSequence: "PET-GCT-AAC-TGA-HEH-EH"
  },
  {
    id: "love_dad",
    name: "Love Dad (Father's Day)",
    filename: "love_dad.png",
    category: "Custom Variant",
    subjectId: "SUB-11",
    pose: "Standing neutral and proud with arms straight down (same pose as normal_stand.png).",
    clothing: "The base outfit, but customized with the custom Thai text 'ปัน ❤️ พ่อ' (Pan loves Dad) printed across the center of the yellow shirt.",
    reference: "Custom Thai Father's Day variant. Dedicated to the ultimate creator (Dad).",
    stability: "100.0% (Perfect Harmony)",
    hazardLevel: "Wholesome / Absolute Safe",
    powerLevel: "∞ (Love Bound)",
    dnaSequence: "DAD-LVE-PAN-TGA-TNY-01"
  }
];
